export interface AnalyticsLabelConstant {
  academic_year: string;
  department: String;
  term: string;
  course_list: string; //nba24
  analytics: string;
  nba22: string;
  search: string;
  fields: string;
  backbtn: string;
  emptyMessage: string;
  chart1_head: string;
  chart2_head: string;
  chart_1_head: string;
  method_col1 : string;
  method_col2 : string;
  method_col3 : string;
  method_col4 : string;
  method_col5_1 : string;
  method_col5_2 : string;
  method_col6 : string;
  method_col7 : string;
  method_col8 : string;
  chart_2_head_web: string;
  chart_2_head_rwd: string;
  sortHead: string;
  totalAtt: string;
  CO: string;
  direct: string;
  name: string;
  desc: string;
  att: string;
  attP: string;
  tot: string;
  totM: string;
  indirect: string;
  method: string;
  SL: string;
  coAtn: string;
  faName: string;
  coName: string;
  Desc: string;
  Asc: string;
  noentry: string;
  one10: string;
  ten20: string;
  twenty30: string;
  colist: string;
  chart_2_header: string;
  avCoAtn: string;
  nba16: string;
  nba17: string;
  chart_1_nba17: string;
  chart_2_nba17: string;
  dialog_heading: string;
  course_level_info: string;
  total_no_lessons: string;
  course_diff_level: string;
  co_specific_info: string;
  co_num: string;
  num_co_mapped_lessons: string;
  co_diff_level: string;
  num_of_lessons_bloom: string;
  bloom_weightage_heading: string;
  totO: string;
  Org: string;
  NAch: string;
  NOrg: string;
  NN: string;
  D: string;
  C: string;
  B: string;
  A: string;
  statement_16:string;
  faculty:string;
  empId:string;
  section:string;
  courseCode:string;
}
